zuul:
  #ignoredServices: "*"
  prefix: /admin
  #routes:
  #  product: /producto/**


  
server:
  port: 4444
  
  
hystrix.command.default.execution.isolation.strategy: THREAD 
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 80000
hystrix.command.default.execution.timeout.enabled: false
hystrix.command.admisiones.execution.timeout.enable: false
hystrix.threadpool.default.coreSize: 50
hystrix.threadpool.default.maxQueueSize: 100
hystrix.threadpool.default.queueSizeRejectionThreshold: 50

ribbon:
# Max number of retries on the same server (excluding the first try)
  maxAutoRetries: 1
# Max number of next servers to retry (excluding the first server)
  MaxAutoRetriesNextServer: 2
# Connect timeout used by Apache HttpClient
  ConnectTimeout: 80000
# Read timeout used by Apache HttpClient
  ReadTimeout: 80000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
