#server:
#  port: 1111
#
#eureka:
#    instance:
#        hostname: localhost
#    client:
#        registerWithEureka: false
#        fetchRegistry: false
#    service-url:
#      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    server:
#    waitTimeInMsWhenSyncEmpty: 0


server:
  port: 1111   # HTTP port
  
# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: true     # Disable Thymeleaf 
  application:
    name: eureka-server
  
logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.app: 'DEBUG'

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
        registerWithEureka: false
        fetchRegistry: true
        service-url:
            default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
