# HTTP Server
server:
  port: 0   # HTTP port

# Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
spring:
    profiles:
         active: native
    datasource:
         url: jdbc:mysql://localhost:3306;database=appa;user=root;password=;
         driver-class-name: com.mysql.jdbc.Driver
#         username: sa
#         password: RootZabudYiin2016
#         Keep the connection alive if idle for a long time (needed in production)
#         time-between-eviction-runs-millis: 60000
#         test-while-idle: true
         test-on-borrow: true
         validation-query: SELECT 1

#logging:
#  file: logs/${spring.application.name}.log
#  level:
#    com.netflix.discovery: 'OFF'
#    org.springframework.cloud: 'DEBUG'
#    com.atsistemas: 'DEBUG'


#spring.datasource.url : jdbc:mysql://localhost:3306/app
#spring.datasource.username : root
#spring.datasource.password :
#spring.datasource.driverClassName : com.mysql.jdbc.Driver